### ISSUE TITLE
card-list

### ISSUE THREAD

**Issue by Leukipos** [Leukipos/Capstone_Project#1]
## Value proposition

As an User
I want to see an overview about the given topics as single cards in a scrollable list-view.
So i can explore the different topics and choose the right one for me.

## Description
![Image](https://user-images.githubusercontent.com/125723244/234536057-4fe4d352-e30f-476b-99f4-768ec38711cb.jpg)
The cards are squares in 2 columns and work as button with a single word which describe the topic.

## Acceptance criteria

- [ ] there are square buttons-list with a single centered word in two collumns
- [ ] they have a friendly, rounded shape and a calming color
- [ ] there are some cards in the list

## Tasks

- [ ] create a new branch
- [ ] create an array with dummy-data
- [ ] create a styled card component
- [ ] adjust the style
- [ ] include the card component in the app

**Comment by Leukipos** [comment]
US 1 correction

**Comment by Roland-Hufnagel** [comment]
this looks already very nice. I have some points to approve:
-In the wireframe there is a burger-menu. If you do not implement it here, it should not be shown.
-In the wireframe I see a header and a footer. This should be mentioned as a task and as an acceptance-criteria
-Your acceptance criteria don't have to be so specific. e.g. "A list of cards is displayed"
-I think you don't use a database right now. As a task you could write "create an array with dummy data"

**Comment by Roland-Hufnagel** [comment]
Hi Alex. This looks clear and good to me.

I would only recommend not to write 'at least 8 cards' because it doesn't matter. Important is to 'display a list of cards'. So you can start with some dummy data that may grow over the time.

Good work!
