### ISSUE TITLE
US 7

### ISSUE THREAD

**Issue by Leukipos** [Leukipos/Capstone_Project#12]
## Value proposition

As an User
I want a Burger Menu
So that i can navigate through the App

## Description
![Bildschirmfoto 2023-05-17 um 10 24 30](https://github.com/Leukipos/Capstone_Project/assets/125723244/94f6639f-8414-4e6d-8b1f-46eaba6c1633)

When the User push the Burger-Menu-Button the app "greys-out" and a List of Link Buttons appear.
The Icon becomes a cross which is usable to close the Menu.

## Acceptance criteria

- [ ] there is a Burger-Menu-Button fixed on the upper right corner
- [ ] by clicking the button the app greys-out and the menu appears
- [ ] the menu contain a list of Link-Entries
- [ ] the links guides to the named content
- [ ] the menu-Icon becomes a cross during the menu is "open"
- [ ] you can close the menu by clicking the cross

## Tasks

- [ ] new feature branch
- [ ] new menu-component
- [ ] implement component to the header
- [ ] make Links work
- [ ] adjust the Style and the behavior of the component
- [ ] open a bottle of beer when successfull
