### ISSUE TITLE
US 8

### ISSUE THREAD

**Issue by Leukipos** [Leukipos/Capstone_Project#14]
## Value proposition

As an User
I want an about, an Introducing  and a Link-page
So that i can get further informations

## Description
![Bildschirmfoto 2023-05-22 um 10 00 51](https://github.com/Leukipos/Capstone_Project/assets/125723244/cb9908da-9cd4-4e3e-a2b3-11491f484831)

- the about-page content all necessary informations about the app and the author
- the SOS-page leads to professional first aid
- the Link-Page is a summary of helpfully contacts

## Acceptance criteria

- [ ] there are some cards with informations on every page
- [ ] every page ist reachable about menu

## Tasks

- [ ] new branch
- [ ] add content to every page

**Comment by doctype-Melvin** [comment]
lgtm
Great app idea btw. 
Feel like I should keep an eye on it.
