### ISSUE TITLE
landing page

### ISSUE THREAD

**Issue by Leukipos** [Leukipos/Capstone_Project#2]
# take my hand APP

# MVP

- calm landing page
- index-site with at least two module-cards
- at least one module have to link to a functionally module-site
- module-site has at least two articles
- flyout for detail-information with dummy-text
- footer with dummy-content
- header with titel
- about-site with dummy informations

# UserStory 001

## Value proposition

As an User
I want a calming landingpage
So that i believe in my desicion to choose this app

## Description

- calming, friendly and warm colors
- reduced design with a good overview - as simple as possible
- a short introducing about the app
- a friendly button who invite me to go further

## Acceptance criteria

- [ ] the reduced design, the colors and the functionality calms me down
- [ ] the page takes me away and i want to go further
- [ ] the indroducing text touch me, so i am feel me right

## Tasks

- [ ] make a scribble
- [ ] investigate a good color palette
- [ ] create a new branch
- [ ] create a new page in VSC
- [ ] preview and test the look and feel
