### ISSUE TITLE
homepage

### ISSUE THREAD

**Issue by Leukipos** [Leukipos/Capstone_Project#3]
## Value proposition

As an User  i want to see a homepage with a titelbar with a a headline and a burger-menu
So that i can see always on wich site i am and have the possibility to choose an other.

## Description
![Bildschirmfoto 2023-04-26 um 09 56 51](https://user-images.githubusercontent.com/125723244/234508732-c7fe61de-bc97-4f20-a092-523d27148f21.jpg)
The centered headline shows the currently selected location and on the right site there is an burger-menu-button.

## Acceptance criteria

- [ ] there is a fixed titel-bar with a centered headline
- [ ] the bar has a fixed position on the top
- [ ] on the right site there is a burger-menu-button

## Tasks

- [ ] create a new branch
- [ ] create a styled-titel-component
- [ ] create a menu-component with at least 3 dummy-entries
- [ ] adjust the style so everything fits the scribble
- [ ] add the component to the app

**Comment by Roland-Hufnagel** [comment]
Please have a look at Niklas suggestions and try to apply it to your userstory

**Comment by t0bbl** [comment]
you still mention the burger menu in the acceptance criteria, otherwise it looks good!
