### ISSUE TITLE
module page

### ISSUE THREAD

**Issue by Leukipos** [Leukipos/Capstone_Project#4]
## Value proposition

As an User
I want to see some short articles there are shown in single cards
So that i can read the content step by step

## Description
![Bildschirmfoto 2023-04-26 um 11 57 38](https://user-images.githubusercontent.com/125723244/234541167-466b515b-616d-45ed-b7d4-8e89719187fe.jpg)
- The Content of every single Topic/Module ist splittet of in single Articles there are shown in cards.

## Acceptance criteria

- [ ] There are different Articles as cards
- [ ] The content of the articles is from the modules Array

## Tasks

- [ ] create a new branch
- [ ] create a styled card component
- [ ] fetch the content from modules Array
- [ ] add the component to the app

**Comment by t0bbl** [comment]
i think you didnt mention your header or how you want to implement it.
looks good to me otherwise.
