### ISSUE TITLE
US 5

### ISSUE THREAD

**Issue by Leukipos** [Leukipos/Capstone_Project#5]
## Value proposition

As an User
I want to see an about, SOS. and contact-page.
So that i can get further informations.

## Description
![Bildschirmfoto 2023-04-26 um 15 07 27](https://user-images.githubusercontent.com/125723244/234585193-72c025e5-6dbc-4a03-9db9-e3ec60433bae.jpg)

- single pages with a couple of cards with informations 

## Acceptance criteria

- [ ] a couple of information-cards with several topics

## Tasks

- [ ] create a new branch
- [ ] create pages
- [ ] use the card-component to render cards
