### ISSUE TITLE
Basic Styling

### ISSUE THREAD

**Issue by Leukipos** [Leukipos/Capstone_Project#7]
## Value proposition

As an User
I want a font that fits to my needs
So that i am feeling well

## Description
![Bildschirmfoto 2023-04-27 um 10 24 14](https://user-images.githubusercontent.com/125723244/234805219-17af9bb5-7b7f-4bab-b889-8ae28f0d022b.jpg)

- the font has to be clear, friendly and calming.

## Acceptance criteria

- [ ] the best performing font is found
- [ ] the font is embedded and selected in the APP

## Tasks

- [ ] select or find a fonts on google fonts that fits
- [ ] download and save the font in the project
- [ ] embed the font in GlobalStyle
